[project]
name = "JSpeak"
version = "0.1.0"
authors = [
    {name = "Marley Mulvin Broome", email = "marley.developer@gmail.com"}
]

[tool.black]
line-length = 80
target-version = ["py39"]
exclude = "(src/lib|src/config.ini)"